name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - run: npm install -g pnpm

      - run: pnpm install

      - run: npm run docs:build

      - name: Check if dist exists
        run: tree

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .vitepress/docs/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
